#!/bin/bash -x
set -x

# TODO: place initializaton steps in testing repository https://github.com/jotelha/dtool-lookup-server-container-composition
# create subfolder on share
smbclient -U guest -c "mkdir dtool" -N -W WORKGROUP //sambaserver/sambashare

# place test dataset on share
dtool cp /share/dtool/simple_test_dataset smb://test-share
dtool cp /share/dtool/simple_test_dataset s3://test-bucket
exit $?
